# Generated by Django 2.1.7 on 2019-08-19 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='traininglead',
            old_name='followup_date',
            new_name='followup',
        ),
        migrations.RemoveField(
            model_name='traininglead',
            name='status',
        ),
    ]
