# Generated by Django 2.1.7 on 2019-08-19 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0002_auto_20190819_0750'),
    ]

    operations = [
        migrations.AddField(
            model_name='traininglead',
            name='status',
            field=models.CharField(default='new', max_length=100),
            preserve_default=False,
        ),
    ]
