# Generated by Django 2.1.7 on 2019-08-19 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0005_auto_20190819_0941'),
    ]

    operations = [
        migrations.AddField(
            model_name='traininglead',
            name='lastfollowup',
            field=models.DateField(null=True),
        ),
    ]
